BOARD_TAG	= leonardo
MONITOR_PORT	= /dev/ttyACM0
USER_LIB_PATH	= $(realpath ../../libraries/)
#ARDUINO_LIB_PATH= $(realpath ../../arduino-1.8.9/hardware/arduino/avr/libraries/)
ARDUINO_DIR	= $(realpath ../../arduino-1.8.9/)
#ARDUINO_LIBS	= HID HID-Project
RESET_CMD	= $(ARDMK_DIR)/bin/ard-reset-arduino --verbose --caterina /dev/ttyACM0

include ../../Arduino.mk
